pizzeria/pizzaria/urls.py
from django.contrib import admin
from django.urls import path, include  # Include is needed to connect app URLs

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),  # Include URLs from the learning_logs app
]

pizzeria/pizzas/urls.py
from django.urls import path
from . import views  # Import views from the current app

app_name = 'pizzas'

urlpatterns = [
    path('', views.home, name='index'),  # Home page URL
    path('pizzas/', views.pizzas, name='pizzas'),  # Topic page URL
    # Detail page for a single topic
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'), 
    # Page for editing an entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

pizzeria/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """A topic the user is learning about"""
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name
    
class Topping(models.Model):
    """Something specific learned about a topic"""
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
            """Return a string representation of the model."""
            return self.name

pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

def home(request):
    """The home page for Pizzas."""
    return render(request, 'pizzas/index.html')  # Render the template

def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and all its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<a href="{% url 'pizzas:index' %}">Pizzas</a> - 
<a href="{% url 'pizzas:pizzas' %}">Types</a>
</p>
{% block content %}{% endblock content %}

pizzeria/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
    <h1>Welcome to Pizzas</h1>
    <p>This is the home page of Pizzas application.</p>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
{% block content %}

	<p>Topic: <b>{{ pizza }}</b></p>

	<h3>Toppings:</h3>
	<ul>
	{% for topping in toppings %}
		<li>
			<p><i>{{ topping.date_added|date:'M d, Y H:i' }}</i></p>
			<p>{{ topping.name|linebreaks }}</p>
		</li>
	{% empty %}
		<li>
		There are no toppings for this pizza yet.
		</li>
		{% endfor %}
	</ul>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% block content %}
	<h3>Pizzas</h3>

	<ul>
		{% for pizza in pizzas %}
			<li>
				<a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
		   </li>
		{% empty %}
			<li>No pizzas have been added yet.</li>
		{% endfor %}
	</ul>
{% endblock content %}